var fire_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Breath Weapon"   ],
  ["1",     "+2",          "",                       "2d6  Fire Damage"],
  ["2",     "+2",          "",                       "3d6  Fire Damage"],
  ["3",     "+2",          "",                       "4d6  Fire Damage"],
  ["4",     "+2",          "Ability Score Increase", "4d6  Fire Damage"],
  ["5",     "+3",          "",                       "5d6  Fire Damage"],
  ["6",     "+3",          "",                       "6d6  Fire Damage"],
  ["7",     "+3",          "",                       "7d6  Fire Damage"],
  ["8",     "+3",          "Ability Score Increase", "7d6  Fire Damage"],
  ["9",     "+4",          "",                       "8d6  Fire Damage"],
  ["10",    "+4",          "",                       "9d6  Fire Damage"],
  ["11",    "+4",          "",                       "10d6 Fire Damage"],
  ["12",    "+4",          "Ability Score Increase", "10d6 Fire Damage"],
  ["13",    "+5",          "",                       "11d6 Fire Damage"],
  ["14",    "+5",          "",                       "12d6 Fire Damage"],
  ["15",    "+5",          "",                       "13d6 Fire Damage"],
  ["16",    "+5",          "Ability Score Increase", "13d6 Fire Damage"],
  ["17",    "+6",          "",                       "14d6 Fire Damage"],
  ["18",    "+6",          "",                       "15d6 Fire Damage"],
  ["19",    "+6",          "Ability Score Increase", "15d6 Fire Damage"],
  ["20",    "+6",          "",                       "16d6 Fire Damage"]
];

var lightning_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Breath Weapon"        ],
  ["1",     "+2",          "",                       "2d6  Lightning Damage"],
  ["2",     "+2",          "",                       "3d6  Lightning Damage"],
  ["3",     "+2",          "",                       "4d6  Lightning Damage"],
  ["4",     "+2",          "Ability Score Increase", "4d6  Lightning Damage"],
  ["5",     "+3",          "",                       "5d6  Lightning Damage"],
  ["6",     "+3",          "",                       "6d6  Lightning Damage"],
  ["7",     "+3",          "",                       "7d6  Lightning Damage"],
  ["8",     "+3",          "Ability Score Increase", "7d6  Lightning Damage"],
  ["9",     "+4",          "",                       "8d6  Lightning Damage"],
  ["10",    "+4",          "",                       "9d6  Lightning Damage"],
  ["11",    "+4",          "",                       "10d6 Lightning Damage"],
  ["12",    "+4",          "Ability Score Increase", "10d6 Lightning Damage"],
  ["13",    "+5",          "",                       "11d6 Lightning Damage"],
  ["14",    "+5",          "",                       "12d6 Lightning Damage"],
  ["15",    "+5",          "",                       "13d6 Lightning Damage"],
  ["16",    "+5",          "Ability Score Increase", "13d6 Lightning Damage"],
  ["17",    "+6",          "",                       "14d6 Lightning Damage"],
  ["18",    "+6",          "",                       "15d6 Lightning Damage"],
  ["19",    "+6",          "Ability Score Increase", "15d6 Lightning Damage"],
  ["20",    "+6",          "",                       "16d6 Lightning Damage"]
];

var ice_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Breath Weapon"   ],
  ["1",     "+2",          "",                       "2d6  Cold Damage"],
  ["2",     "+2",          "",                       "3d6  Cold Damage"],
  ["3",     "+2",          "",                       "4d6  Cold Damage"],
  ["4",     "+2",          "Ability Score Increase", "4d6  Cold Damage"],
  ["5",     "+3",          "",                       "5d6  Cold Damage"],
  ["6",     "+3",          "",                       "6d6  Cold Damage"],
  ["7",     "+3",          "",                       "7d6  Cold Damage"],
  ["8",     "+3",          "Ability Score Increase", "7d6  Cold Damage"],
  ["9",     "+4",          "",                       "8d6  Cold Damage"],
  ["10",    "+4",          "",                       "9d6  Cold Damage"],
  ["11",    "+4",          "",                       "10d6 Cold Damage"],
  ["12",    "+4",          "Ability Score Increase", "10d6 Cold Damage"],
  ["13",    "+5",          "",                       "11d6 Cold Damage"],
  ["14",    "+5",          "",                       "12d6 Cold Damage"],
  ["15",    "+5",          "",                       "13d6 Cold Damage"],
  ["16",    "+5",          "Ability Score Increase", "13d6 Cold Damage"],
  ["17",    "+6",          "",                       "14d6 Cold Damage"],
  ["18",    "+6",          "",                       "15d6 Cold Damage"],
  ["19",    "+6",          "Ability Score Increase", "15d6 Cold Damage"],
  ["20",    "+6",          "",                       "16d6 Cold Damage"]
];

var death_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Essence Siphon"     ],
  ["1",     "+2",          "",                       "1d6 Necrotic Damage"],
  ["2",     "+2",          "",                       "1d6 Necrotic Damage"],
  ["3",     "+2",          "",                       "1d6 Necrotic Damage"],
  ["4",     "+2",          "Ability Score Increase", "2d6 Necrotic Damage"],
  ["5",     "+3",          "",                       "2d6 Necrotic Damage"],
  ["6",     "+3",          "",                       "2d6 Necrotic Damage"],
  ["7",     "+3",          "",                       "3d6 Necrotic Damage"],
  ["8",     "+3",          "Ability Score Increase", "3d6 Necrotic Damage"],
  ["9",     "+4",          "",                       "3d6 Necrotic Damage"],
  ["10",    "+4",          "",                       "4d6 Necrotic Damage"],
  ["11",    "+4",          "",                       "4d6 Necrotic Damage"],
  ["12",    "+4",          "Ability Score Increase", "4d6 Necrotic Damage"],
  ["13",    "+5",          "",                       "5d6 Necrotic Damage"],
  ["14",    "+5",          "",                       "5d6 Necrotic Damage"],
  ["15",    "+5",          "",                       "5d6 Necrotic Damage"],
  ["16",    "+5",          "Ability Score Increase", "6d6 Necrotic Damage"],
  ["17",    "+6",          "",                       "6d6 Necrotic Damage"],
  ["18",    "+6",          "",                       "6d6 Necrotic Damage"],
  ["19",    "+6",          "Ability Score Increase", "7d6 Necrotic Damage"],
  ["20",    "+6",          "",                       "7d6 Necrotic Damage"]
];

var rock_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Non-Magical Damage Reduction"],
  ["1",     "+2",          "",                       "-0 Damage"                   ],
  ["2",     "+2",          "",                       "-0 Damage"                   ],
  ["3",     "+2",          "",                       "-1 Damage"                   ],
  ["4",     "+2",          "Ability Score Increase", "-1 Damage"                   ],
  ["5",     "+3",          "",                       "-2 Damage"                   ],
  ["6",     "+3",          "",                       "-2 Damage"                   ],
  ["7",     "+3",          "",                       "-3 Damage"                   ],
  ["8",     "+3",          "Ability Score Increase", "-3 Damage"                   ],
  ["9",     "+4",          "",                       "-4 Damage"                   ],
  ["10",    "+4",          "",                       "-4 Damage"                   ],
  ["11",    "+4",          "",                       "-5 Damage"                   ],
  ["12",    "+4",          "Ability Score Increase", "-5 Damage"                   ],
  ["13",    "+5",          "",                       "-6 Damage"                   ],
  ["14",    "+5",          "",                       "-6 Damage"                   ],
  ["15",    "+5",          "",                       "-7 Damage"                   ],
  ["16",    "+5",          "Ability Score Increase", "-7 Damage"                   ],
  ["17",    "+6",          "",                       "-8 Damage"                   ],
  ["18",    "+6",          "",                       "-8 Damage"                   ],
  ["19",    "+6",          "Ability Score Increase", "-9 Damage"                   ],
  ["20",    "+6",          "",                       "-9 Damage"                   ]
];
