var fire_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Breath Weapon"                            ],
  ["1",     "+2",          "",                       "7\xa0\xa0\xa0(2d6)\xa0\xa0\xa0Fire Damage"],
  ["2",     "+2",          "",                       "11\xa0(3d6)\xa0\xa0\xa0Fire Damage"       ],
  ["3",     "+2",          "",                       "14\xa0(4d6)\xa0\xa0\xa0Fire Damage"       ],
  ["4",     "+2",          "Ability Score Increase", "14\xa0(4d6)\xa0\xa0\xa0Fire Damage"       ],
  ["5",     "+3",          "Extra Attack",           "18\xa0(5d6)\xa0\xa0\xa0Fire Damage"       ],
  ["6",     "+3",          "",                       "21\xa0(6d6)\xa0\xa0\xa0Fire Damage"       ],
  ["7",     "+3",          "",                       "25\xa0(7d6)\xa0\xa0\xa0Fire Damage"       ],
  ["8",     "+3",          "Ability Score Increase", "25\xa0(7d6)\xa0\xa0\xa0Fire Damage"       ],
  ["9",     "+4",          "",                       "28\xa0(8d6)\xa0\xa0\xa0Fire Damage"       ],
  ["10",    "+4",          "",                       "32\xa0(9d6)\xa0\xa0\xa0Fire Damage"       ],
  ["11",    "+4",          "Extra Attack (2)",       "35\xa0(10d6)\xa0Fire Damage"              ],
  ["12",    "+4",          "Ability Score Increase", "35\xa0(10d6)\xa0Fire Damage"              ],
  ["13",    "+5",          "",                       "39\xa0(11d6)\xa0Fire Damage"              ],
  ["14",    "+5",          "",                       "42\xa0(12d6)\xa0Fire Damage"              ],
  ["15",    "+5",          "",                       "46\xa0(13d6)\xa0Fire Damage"              ],
  ["16",    "+5",          "Ability Score Increase", "46\xa0(13d6)\xa0Fire Damage"              ],
  ["17",    "+6",          "",                       "49\xa0(14d6)\xa0Fire Damage"              ],
  ["18",    "+6",          "",                       "53\xa0(15d6)\xa0Fire Damage"              ],
  ["19",    "+6",          "Ability Score Increase", "53\xa0(15d6)\xa0Fire Damage"              ],
  ["20",    "+6",          "Extra Attack (3)",       "56\xa0(16d6)\xa0Fire Damage"              ]
];

var lightning_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Breath Weapon"                                 ],
  ["1",     "+2",          "",                       "7\xa0\xa0\xa0(2d6)\xa0\xa0\xa0Lightning Damage"],
  ["2",     "+2",          "",                       "11\xa0(3d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["3",     "+2",          "",                       "14\xa0(4d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["4",     "+2",          "Ability Score Increase", "14\xa0(4d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["5",     "+3",          "Extra Attack",           "18\xa0(5d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["6",     "+3",          "",                       "21\xa0(6d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["7",     "+3",          "",                       "25\xa0(7d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["8",     "+3",          "Ability Score Increase", "25\xa0(7d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["9",     "+4",          "",                       "28\xa0(8d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["10",    "+4",          "",                       "32\xa0(9d6)\xa0\xa0\xa0Lightning Damage"       ],
  ["11",    "+4",          "Extra Attack (2)",       "35\xa0(10d6)\xa0Lightning Damage"              ],
  ["12",    "+4",          "Ability Score Increase", "35\xa0(10d6)\xa0Lightning Damage"              ],
  ["13",    "+5",          "",                       "39\xa0(11d6)\xa0Lightning Damage"              ],
  ["14",    "+5",          "",                       "42\xa0(12d6)\xa0Lightning Damage"              ],
  ["15",    "+5",          "",                       "46\xa0(13d6)\xa0Lightning Damage"              ],
  ["16",    "+5",          "Ability Score Increase", "46\xa0(13d6)\xa0Lightning Damage"              ],
  ["17",    "+6",          "",                       "49\xa0(14d6)\xa0Lightning Damage"              ],
  ["18",    "+6",          "",                       "53\xa0(15d6)\xa0Lightning Damage"              ],
  ["19",    "+6",          "Ability Score Increase", "53\xa0(15d6)\xa0Lightning Damage"              ],
  ["20",    "+6",          "Extra Attack (3)",       "56\xa0(16d6)\xa0Lightning Damage"              ]
];

var ice_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Breath Weapon"                            ],
  ["1",     "+2",          "",                       "7\xa0\xa0\xa0(2d6)\xa0\xa0\xa0Cold Damage"],
  ["2",     "+2",          "",                       "11\xa0(3d6)\xa0\xa0\xa0Cold Damage"       ],
  ["3",     "+2",          "",                       "14\xa0(4d6)\xa0\xa0\xa0Cold Damage"       ],
  ["4",     "+2",          "Ability Score Increase", "14\xa0(4d6)\xa0\xa0\xa0Cold Damage"       ],
  ["5",     "+3",          "Extra Attack",           "18\xa0(5d6)\xa0\xa0\xa0Cold Damage"       ],
  ["6",     "+3",          "",                       "21\xa0(6d6)\xa0\xa0\xa0Cold Damage"       ],
  ["7",     "+3",          "",                       "25\xa0(7d6)\xa0\xa0\xa0Cold Damage"       ],
  ["8",     "+3",          "Ability Score Increase", "25\xa0(7d6)\xa0\xa0\xa0Cold Damage"       ],
  ["9",     "+4",          "",                       "28\xa0(8d6)\xa0\xa0\xa0Cold Damage"       ],
  ["10",    "+4",          "",                       "32\xa0(9d6)\xa0\xa0\xa0Cold Damage"       ],
  ["11",    "+4",          "Extra Attack (2)",       "35\xa0(10d6)\xa0Cold Damage"              ],
  ["12",    "+4",          "Ability Score Increase", "35\xa0(10d6)\xa0Cold Damage"              ],
  ["13",    "+5",          "",                       "39\xa0(11d6)\xa0Cold Damage"              ],
  ["14",    "+5",          "",                       "42\xa0(12d6)\xa0Cold Damage"              ],
  ["15",    "+5",          "",                       "46\xa0(13d6)\xa0Cold Damage"              ],
  ["16",    "+5",          "Ability Score Increase", "46\xa0(13d6)\xa0Cold Damage"              ],
  ["17",    "+6",          "",                       "49\xa0(14d6)\xa0Cold Damage"              ],
  ["18",    "+6",          "",                       "53\xa0(15d6)\xa0Cold Damage"              ],
  ["19",    "+6",          "Ability Score Increase", "53\xa0(15d6)\xa0Cold Damage"              ],
  ["20",    "+6",          "Extra Attack (3)",       "56\xa0(16d6)\xa0Cold Damage"              ]
];

var death_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Essence Siphon"                    ],
  ["1",     "+2",          "",                       "4\xa0\xa0\xa0(1d6) Necrotic Damage"],
  ["2",     "+2",          "",                       "4\xa0\xa0\xa0(1d6) Necrotic Damage"],
  ["3",     "+2",          "",                       "4\xa0\xa0\xa0(1d6) Necrotic Damage"],
  ["4",     "+2",          "Ability Score Increase", "7\xa0\xa0\xa0(2d6) Necrotic Damage"],
  ["5",     "+3",          "Extra Attack",           "7\xa0\xa0\xa0(2d6) Necrotic Damage"],
  ["6",     "+3",          "",                       "7\xa0\xa0\xa0(2d6) Necrotic Damage"],
  ["7",     "+3",          "",                       "11\xa0(3d6) Necrotic Damage"       ],
  ["8",     "+3",          "Ability Score Increase", "11\xa0(3d6) Necrotic Damage"       ],
  ["9",     "+4",          "",                       "11\xa0(3d6) Necrotic Damage"       ],
  ["10",    "+4",          "",                       "14\xa0(4d6) Necrotic Damage"       ],
  ["11",    "+4",          "Extra Attack (2)",       "14\xa0(4d6) Necrotic Damage"       ],
  ["12",    "+4",          "Ability Score Increase", "14\xa0(4d6) Necrotic Damage"       ],
  ["13",    "+5",          "",                       "18\xa0(5d6) Necrotic Damage"       ],
  ["14",    "+5",          "",                       "18\xa0(5d6) Necrotic Damage"       ],
  ["15",    "+5",          "",                       "18\xa0(5d6) Necrotic Damage"       ],
  ["16",    "+5",          "Ability Score Increase", "21\xa0(6d6) Necrotic Damage"       ],
  ["17",    "+6",          "",                       "21\xa0(6d6) Necrotic Damage"       ],
  ["18",    "+6",          "",                       "21\xa0(6d6) Necrotic Damage"       ],
  ["19",    "+6",          "Ability Score Increase", "25\xa0(7d6) Necrotic Damage"       ],
  ["20",    "+6",          "Extra Attack (3)",       "25\xa0(7d6) Necrotic Damage"       ]
];

var rock_wyvern_level_chart = [
  ["Level", "Proficiency", "Features",               "Non-Magical Damage Reduction"],
  ["1",     "+2",          "",                       "-0 Damage"                   ],
  ["2",     "+2",          "",                       "-0 Damage"                   ],
  ["3",     "+2",          "",                       "-1 Damage"                   ],
  ["4",     "+2",          "Ability Score Increase", "-1 Damage"                   ],
  ["5",     "+3",          "Extra Attack",           "-2 Damage"                   ],
  ["6",     "+3",          "",                       "-2 Damage"                   ],
  ["7",     "+3",          "",                       "-3 Damage"                   ],
  ["8",     "+3",          "Ability Score Increase", "-3 Damage"                   ],
  ["9",     "+4",          "",                       "-4 Damage"                   ],
  ["10",    "+4",          "",                       "-4 Damage"                   ],
  ["11",    "+4",          "Extra Attack (2)",       "-5 Damage"                   ],
  ["12",    "+4",          "Ability Score Increase", "-5 Damage"                   ],
  ["13",    "+5",          "",                       "-6 Damage"                   ],
  ["14",    "+5",          "",                       "-6 Damage"                   ],
  ["15",    "+5",          "",                       "-7 Damage"                   ],
  ["16",    "+5",          "Ability Score Increase", "-7 Damage"                   ],
  ["17",    "+6",          "",                       "-8 Damage"                   ],
  ["18",    "+6",          "",                       "-8 Damage"                   ],
  ["19",    "+6",          "Ability Score Increase", "-9 Damage"                   ],
  ["20",    "+6",          "Extra Attack (3)",       "-9 Damage"                   ]
];
